networks:
   jklu_cyber_lab:
     external: true
     name: "jklu_cyber_lab"

services:
  kalilinux:
    image: kalilinux/kali-rolling
    container_name: jklu_attacker
    stdin_open: true
    tty: true
    networks:
      - jklu_cyber_lab
    restart: unless-stopped
